ppw_stories/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("story_5/",include("story_5.urls")),
    path("story_6/",include("story_6.urls")),
    path("",views.blank_page)
]

story_5/urls.py
from django.urls import path
from . import views
from .views import index, add_matkul, matkul_detail, delete_matkul

app_name = "story_5"

urlpatterns = [
    path("",views.index,name="index"),
    path("add_matkul/",views.add_matkul,name="add_matkul"),
    path("matkul/<int:id>",views.matkul_detail,name="matkul_detail"),
    path("delete_matkul/<int:id>",views.delete_matkul,name="delete_matkul")
]

story_5/models.py
from django.db import models
from django.shortcuts import reverse
from django.utils import timezone

semester_choices = [
    ("2019/2020 Gasal","2019/2020 Gasal"),
    ("2019/2020 Genap","2019/2020 Genap"),
    ("2020/2021 Gasal","2020/2021 Gasal"),
    ("2020/2021 Genap","2020/2021 Genap"),
    ("2021/2022 Gasal","2021/2022 Gasal"),
    ("2021/2022 Genap","2021/2022 Genap"),
    ("2022/2023 Gasal","2022/2023 Gasal"),
    ("2022/2023 Genap","2022/2023 Genap")
]

class MataKuliah(models.Model):
    nama = models.TextField(max_length = 50)
    dosen = models.TextField(max_length = 50)
    jumlah_sks = models.IntegerField()
    deskripsi = models.TextField(max_length = 500)
    semester = models.TextField(choices = semester_choices)
    ruangan = models.TextField(max_length = 50)

    def __str__(self):
        return "{} ({})".format(self.nama,self.dosen)

    def get_absolute_url(self):
        return reverse("story_5:matkul_detail",args=[self.id])

class TugasMataKuliah(models.Model):
    nama = models.TextField(max_length=50)
    deadline = models.DateTimeField()
    mata_kuliah = models.ForeignKey(MataKuliah,on_delete=models.CASCADE)

    def __str__(self):
        return "{} - {}".format(self.nama,self.mata_kuliah.nama)

story_5/forms.py
from django import forms
from .models import MataKuliah

class MatkulForm(forms.ModelForm):
    class Meta:
        model = MataKuliah
        fields = "__all__"

story_5/views.py
from django.shortcuts import render, redirect
from .models import MataKuliah, TugasMataKuliah
from .forms import MatkulForm
from django.utils import timezone
from django.contrib import messages

def index(request):
    context = {
        "mata_kuliah_list" : MataKuliah.objects.all().order_by("-id"),
        "page" : "index"
    }
    return render(request,"story_5/index.html",context)

def add_matkul(request):
    if request.method == "POST":
        matkul_form = MatkulForm(request.POST)
        if matkul_form.is_valid():
            matkul_form.save()
            messages.add_message(request, messages.SUCCESS, "Mata Kuliah '{}' successfully added".format(request.POST["nama"]))
        return redirect("story_5:index")
    context = {
        "page" : "add_page"
    }
    return render(request,"story_5/add_matkul.html",context)

def matkul_detail(request,id):
    matkul = MataKuliah.objects.get(id=id)
    context = {
        "mata_kuliah" : matkul,
        "tugas_objects" : TugasMataKuliah.objects.filter(mata_kuliah=matkul).order_by("deadline"),
        "time_now" : timezone.now()
    }

    tugas_deadline = []
    for matkul in context["tugas_objects"]:
        diff = matkul.deadline - timezone.now()  
        tugas_deadline.append((matkul,diff.total_seconds())) #get detik perbedaan
    context["matkul_deadlines"] = tugas_deadline
    return render(request,"story_5/detail_matkul.html",context)

def delete_matkul(request,id):
    if request.method == "POST":
        mata_kuliah = MataKuliah.objects.get(id=id)
        mata_kuliah.delete()
        messages.add_message(request, messages.SUCCESS, "Mata Kuliah '{}' successfully deleted".format(mata_kuliah.nama))
    return redirect("story_5:index")

story_5/templates/story_5/add_matkul.html
{% extends 'story_5/base.html' %}
{% block content %}
<div class="main pt-3">
    <div class="container">
        <div class="matkul-card p-3 rounded-lg mb-3">
          <form method="POST" action="{% url 'story_5:add_matkul' %}">
            {% csrf_token %}
            <div class="d-flex row mb-1">
              <div class=" col-sm-12 col-lg-9 d-flex justify-content-center justify-content-lg-start align-items-center">
                <input class="form-control-lg col-9 mb-3 form-transparent p-0 nama-input" placeholder="Nama mata kuliah" name="nama" required>
              </div>
              <div class=" col-sm-12 col-lg-3 d-flex justify-content-center align-items-center w-100">
                <button class="btn btn-primary" type="submit">Add Matkul</button>
              </div>
              </div>
              <div class="row">
              <div class="col-lg-8 border-right">
                <div class="d-flex justify-content-start align-items-center flex-row mb-1">
                  <p class="p-0 m-0">Ruangan: </p>
                  <input class="form-control-sm w-75 ml-1 form-transparent" placeholder="Kode Ruangan" name="ruangan" required>
                </div>
                <div class="d-flex justify-content-start align-items-center flex-row">
                  <p class="p-0 m-0 ">Dibawa oleh: </p>
                  <input class="form-control-sm w-75 ml-1 form-transparent" placeholder="Nama dosen" name="dosen" required>
                </div>
              </div>
              <div class="col-lg-4">
                <select class="form-control mb-1" name="semester" required>
                  <option value="2019/2020 Gasal">2019/2020 Gasal</option>
                  <option value="2019/2020 Genap">2019/2020 Genap</option>
                  <option value="2020/2021 Gasal">2020/2021 Gasal</option>
                  <option value="2020/2021 Genap">2020/2021 Genap</option>
                  <option value="2021/2022 Gasal">2021/2022 Gasal</option>
                  <option value="2021/2022 Genap">2021/2022 Genap</option>
                  <option value="2022/2023 Gasal">2022/2023 Gasal</option>
                  <option value="2022/2023 Genap">2022/2023 Genap</option>
                </select>
                <div class="d-flex justify-content-lg-start align-items-center flex-row">
                  <input class="form-control mr-1 sks-input" type="number" value=1 name="jumlah_sks" required>
                  <p class="p-0 m-0">SKS</p>
                </div>
              </div>
            </div>

            <div class="desc p-2 mt-2 rounded-lg">
              <textarea class="form-control w-100 form-transparent description-input" placeholder="Description of Mata Kuliah" name="deskripsi" required></textarea>
            </div>
          </form>
        </div>
    </div>
</div>
{% endblock %}

story_5/templates/story_5/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- External CSS -->
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>Mata Kuliah Organizer</title>
  </head>
  <body>
      <nav class="navbar navbar-expand-lg navbar-dark bg-siak">
        <div class="container">
            <a class="navbar-brand" href={% url 'story_5:index' %}><span class="nav-title">Matkul <span class="text-light">Organizer</span></span></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
                {% if page == "index" %}
                  <li class="nav-item active">
                  <a class="nav-link" href={% url 'story_5:index' %}>Home</a>
                  </li>
                  <li class="nav-item">
                  <a class="nav-link" href={% url 'story_5:add_matkul' %}>Add Matkul</a>
                  </li>
                {% elif page == "add_page" %}
                  <li class="nav-item">
                  <a class="nav-link" href={% url 'story_5:index' %}>Home</a>
                  </li>
                  <li class="nav-item active">
                  <a class="nav-link" href={% url 'story_5:add_matkul' %}>Add Matkul</a>
                  </li>
                {% else %}
                  <li class="nav-item">
                  <a class="nav-link" href={% url 'story_5:index' %}>Home</a>
                  </li>
                  <li class="nav-item">
                  <a class="nav-link" href={% url 'story_5:add_matkul' %}>Add Matkul</a>
                  </li>
                {% endif %}
            </ul>
            </div>
        </div>
    </nav>
  
    {% block content %}
    {% endblock %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

story_5/templates/story_5/detail_matkul.html
{% extends 'story_5/base.html' %}
{% block content %}
<div class="main pt-3">
    <div class="container">
        <div class="matkul-card p-3 rounded-lg mb-3">
          <h3 class="p-0 m-0">{{mata_kuliah.nama}}</h3>
          <div class="row">
            <div class="col-lg-8 border-right">
              <p class="p-0 m-0">Ruangan: {{mata_kuliah.ruangan}}</p>
              <p class="p-0 m-0">Dibawa oleh {{mata_kuliah.dosen}}</p>
            </div>
            <div class="col-lg-4">
              <p class="p-0 m-0">{{mata_kuliah.semester}}</p>
              <p class="p-0 m-0">{{mata_kuliah.jumlah_sks}} SKS</p>
            </div>
          </div>

          <div class="desc p-2 mt-2 rounded-lg">
            {{mata_kuliah.deskripsi}}
          </div>
          <h3 class="my-2">Tugas list:</h3>
          <div class="row p-2">
            {% for tugas in matkul_deadlines %}
              <div class="p-2 col-lg-3 col-sm-12 p-5 text-center
                {% if tugas.1 < 0 %}
                bg-secondary
                {% elif tugas.1 < 86400 %}
                bg-danger
                {% elif tugas.1 < 604800 %}
                bg-info
                {% else %}
                bg-success
                {% endif %}
              ">
                <h4 class="p-0 m-0">{{tugas.0.nama}}</h4>
                <p class="p-0 m-0">{{tugas.0.deadline}}</p>

                {% if tugas.1 < 0 %}
                <p>deadline passed</p>
                {% elif tugas.1 < 86400 %}
                <p>deadline within 24 hours</p>
                {% elif tugas.1 < 604800 %}
                <p>deadline within 1 week</p>
                {% else %}
                <p>still a plenty of time</p>
                {% endif %}
              </div>
            {% endfor %}
          </div>
        </div>
    </div>
</div>
{% endblock %}

story_5/templates/story_5/index.html
{% extends 'story_5/base.html' %}
{% block content %}
<div class="main pt-3">
    <div class="container">
        {% if messages %}
            {% for message in messages %}
                    <div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
                        {{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% endfor %}
        {% endif %}

        {% for mata_kuliah in mata_kuliah_list %}
        <div class="matkul-card p-3 row rounded-lg mb-3">
            <div class="col-9">
                <h2 class="p-0 m-0">
                    <a class="matkul-title" href={{mata_kuliah.get_absolute_url}}>
                        {{mata_kuliah.nama}}
                    </a>
                </h2>
                <p class="p-0 m-0">Ruangan: {{mata_kuliah.ruangan}}</p>
                <p class="p-0 m-0">Dibawa oleh {{mata_kuliah.dosen}}</p>
            </div>
            <div class="col-3 d-flex justify-content-center align-items-center">
                <form action="{% url 'story_5:delete_matkul' mata_kuliah.id %}" method="POST">
                    {% csrf_token %}
                    <button class="btn btn-danger" type="input">
                        Delete Mata Kuliah
                    </button>
                </form>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}