ppw_stories/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("story_5/",include("story_5.urls")),
    path("story_6/",include("story_6.urls")),
    path("",views.blank_page)
]

story_5/urls.py
from django.urls import path
from . import views
from .views import index, add_matkul, matkul_detail, delete_matkul

app_name = "story_5"

urlpatterns = [
    path("",views.index,name="index"),
    path("add_matkul/",views.add_matkul,name="add_matkul"),
    path("matkul/<int:id>",views.matkul_detail,name="matkul_detail"),
    path("delete_matkul/<int:id>",views.delete_matkul,name="delete_matkul")
]

story_6/urls.py
from django.urls import path
from . import views

app_name = "story_6"

urlpatterns = [
    path("",views.index,name="home"),
    path("add_peserta/<int:id>",views.add_peserta,name="add_peserta"),
    path("profile/<str:nama>",views.detail_peserta,name="detail_peserta"),
    path("kegiatan/<str:nama>",views.detail_kegiatan,name="detail_kegiatan"),
    path("add_kegiatan/",views.add_kegiatan, name="add_kegiatan"),
    path("delete_peserta/",views.delete_peserta, name="delete_kegiatan")
]

story_6/models.py
from django.db import models
from django.shortcuts import reverse

class Peserta(models.Model):
    nama = models.TextField(max_length=100, unique=True)

    def __str__(self):
        return self.nama
    
    def get_absolute_url(self):
        nama_link = self.nama.replace(" ","-")
        return reverse("story_6:detail_peserta",args=[nama_link])

class Kegiatan(models.Model):
    nama = models.TextField(max_length=100,unique=True)
    peserta = models.ManyToManyField(Peserta,blank=True)

    def __str__(self):
        return self.nama

    def get_absolute_url(self):
        nama_link = self.nama.replace(" ","-")
        return reverse("story_6:detail_kegiatan",args=[nama_link])

story_6/forms.py
from django import forms
from .models import Kegiatan, Peserta

class PesertaForm(forms.ModelForm):
    nama = forms.CharField(widget=forms.TextInput(attrs={"class":"form-control",
        "placeholder" : "Peserta Name"
    }), label = "")
    class Meta:
        model = Peserta
        fields = "__all__"

class KegiatanForm(forms.ModelForm):
    nama = forms.CharField(widget=forms.TextInput(attrs = {"class":"form-control w-50 text-center",
        "placeholder" : "Nama Kegiatan"
    }), label = "")
    class Meta:
        model = Kegiatan
        exclude = ["peserta"]

story_6/views.py
from django.shortcuts import render, HttpResponse, redirect, get_object_or_404, reverse
from .models import Peserta, Kegiatan
from django.contrib import messages
from .forms import PesertaForm, KegiatanForm

def index(request):
    context = {
        "kegiatan_items" : Kegiatan.objects.all(),
        "peserta_form" : PesertaForm,
        "is_index" : True
    }
    return render(request,"story_6/index.html",context)

def add_peserta(request,id):
    if request.method == "POST":
        kegiatan = Kegiatan.objects.get(id=id)
        nama_peserta_baru = request.POST["nama"]

        peserta_baru, status_baru = Peserta.objects.get_or_create(nama=nama_peserta_baru)
        if status_baru:
            peserta_baru.save()
            kegiatan.peserta.add(peserta_baru) # Add peserta baru yang tidak pernah ada.
            messages.add_message(request, messages.SUCCESS, "{} was successfully added to {}".format(nama_peserta_baru,kegiatan.nama))
        else:
            try:
                kegiatan.peserta.get(nama=nama_peserta_baru) # Jangan add peserta yang sudah di kegiatan.
                messages.add_message(request, messages.WARNING, "{} is already a participant in {}".format(nama_peserta_baru,kegiatan.nama))
            except:
                kegiatan.peserta.add(peserta_baru) # Add peserta baru yang ada di database tapi tidak di kegiatan.
                messages.add_message(request, messages.SUCCESS, "{} was successfully added to {}".format(nama_peserta_baru,kegiatan.nama))
    return redirect(reverse("story_6:detail_kegiatan",args=[kegiatan.nama.replace(" ","-")]))

def detail_peserta(request,nama):
    nama = nama.replace("-"," ")
    peserta = get_object_or_404(Peserta,nama=nama)
    context = {
        "peserta" : peserta
    }
    return render(request,"story_6/peserta_detail.html",context)

def detail_kegiatan(request,nama):
    nama = nama.replace("-"," ")
    kegiatan = get_object_or_404(Kegiatan,nama=nama)
    context = {
        "kegiatan" : kegiatan,
        "peserta_form" : PesertaForm
    }
    return render(request,"story_6/kegiatan_detail.html",context)

def add_kegiatan(request):
    if request.method == "POST":
        kegiatan_form = KegiatanForm(request.POST)
        if kegiatan_form.is_valid():
            kegiatan_object = kegiatan_form.save(commit=False)
            slug = kegiatan_object.nama.replace(" ", "-")
            kegiatan_form.save()
        return redirect(reverse("story_6:detail_kegiatan",args=[slug]))

    context = {
        "kegiatan_form" : KegiatanForm,
        "is_add_kegiatan" : True
    }
    return render(request,"story_6/add_kegiatan.html",context)

def delete_peserta(request):
    if request.method == "POST":
        try:
            peserta = Peserta.objects.get(nama = request.POST["nama"])
            kegiatan = Kegiatan.objects.get(id = request.POST["kegiatan_id"])
        except:
            messages.add_message(request, messages.WARNING, "{} was not found on {} as a participant.".format(request.POST["nama"], request.POST["kegiatan_id"]))
            return redirect("story_6:home")
        kegiatan.peserta.remove(peserta)
        messages.add_message(request, messages.SUCCESS, "{} has been removed from {}.".format(peserta.nama, kegiatan.nama))
    return redirect("story_6:home")
    

story_6/templates/story_6/add_kegiatan.html
{% extends "story_6/base.html" %}
{% block content %}

<div>
    <form class="d-flex justify-content-center align-items-center flex-column" action="{% url 'story_6:add_kegiatan' %}" method="POST">
        <h3>Add your Own Kegiatan :)</h3>
        {% csrf_token %}
        {{kegiatan_form}}
        <input class="btn btn-secondary mt-2" type="submit" value="Add Kegiatan">
    </form>
</div>

{% endblock %}

story_6/templates/story_6/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <!-- External CSS -->
    <link rel="stylesheet" href={% static 'css/styles6.css' %}>
    <title>Event Organizer</title>
  </head>
  <body class="min-vh-100 bg-light contain">
    <nav class="navbar navbar-expand-lg navbar-dark bg-secondary">
        <div class="container">
            <a class="navbar-brand" href="{% url 'story_6:home' %}">Event Organizer</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                  <a class="nav-link
                    {% if is_index %}
                      active
                    {% endif %}
                  " href="{% url 'story_6:home' %}">Event List</a>
                </li>
                <li>
                  <a class="nav-link
                    {% if is_add_kegiatan %}
                      active
                    {% endif %}
                  " href="{% url 'story_6:add_kegiatan' %}">Add Kegiatan</a>
                </li>
            </ul>
            </div>
        </div>
    </nav>

    <div class="container pt-3">

      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-{{message.tags}} alert-dismissible fade show mx-2" role="alert">
              {{message}}
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
          </div>
        {% endfor %}
      {% endif %}


    {% block content %}
    {% endblock %}
    </div>
    
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

story_6/templates/story_6/index.html
{% extends "story_6/base.html" %}
{% block content %}
        <div class="row px-2">
            {% for kegiatan in kegiatan_items %}
            <div class="col-lg-4 col-md-6 col-sm-12">
                <div class="bg-secondary p-2 rounded-lg text-light d-flex justify-content-center align-items-center flex-column mb-3 border border-dark">
                    <h3><a class="card-content" href="{{kegiatan.get_absolute_url}}">{{kegiatan.nama}}</a></h3>
                    <h5>Peserta:</h5>
                    <div class="overflow-auto name-list">
                        <ol class="px-5">
                            <form action="{% url 'story_6:delete_kegiatan' %}" method="POST">
                                {% csrf_token %}
                                <input type="hidden" value={{kegiatan.id}} name="kegiatan_id">
                                {% for peserta in kegiatan.peserta.all %}
                                    <li><a class="card-content" href="{{peserta.get_absolute_url}}">{{peserta.nama}}</a><button class="ml-1 px-1 text-light border-0 p-0 bg-danger d-inline" value="{{peserta.nama}}" name="nama" type="submit">X</button></li>
                                {% endfor %}
                            </form>
                        </ol>
                    </div>
                    <div>
                        <form action="{% url 'story_6:add_peserta' id=kegiatan.id %}" method="POST" class="d-flex justify-content-center align-items-center flex-column mt-2">
                            {% csrf_token %}
                            {{peserta_form}}
                            <input class="btn btn-light mt-2" type="submit" value="Add Peserta">
                        </form>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
{% endblock %}

story_6/templates/story_6/kegiatan_detail.html
{% extends "story_6/base.html" %}
{% block content %}
        <div class="row">
            <div class="col-lg-8 col-sm-12">
                <h1>
                    <a class="card-content" href="{{kegiatan.get_absolute_url}}">{{kegiatan.nama}}</a>
                </h1>
                <ol class="px-5">
                    <form action="{% url 'story_6:delete_kegiatan' %}" method="POST">
                        {% csrf_token %}
                        <input type="hidden" value={{kegiatan.id}} name="kegiatan_id">
                        {% for peserta in kegiatan.peserta.all %}
                            <li><a class="card-content" href="{{peserta.get_absolute_url}}">{{peserta.nama}}</a><button class="ml-1 px-1 text-light border-0 p-0 bg-danger d-inline" value="{{peserta.nama}}" name="nama" type="submit">X</button></li>
                        {% endfor %}
                    </form>
                </ol>
            </div>
            <div class="col-lg-4 col-sm-12">
                <div class="bg-secondary p-3 rounded-lg text-light text-center">
                    <h3>Add Peserta</h3>
                    <form action="{% url 'story_6:add_peserta' id=kegiatan.id %}" method="POST" class="d-flex justify-content-center align-items-center flex-column mt-2">
                        {% csrf_token %}
                        {{peserta_form}}
                        <input class="btn btn-light mt-2" type="submit" value="Add Peserta">
                    </form>
                </div>
            </div>
        </div>
{% endblock %}

story_6/templates/story_6/peserta_detail.html
{% extends "story_6/base.html" %}
{% block content %}
        <h1>Profile for {{peserta.nama}}</h1>
        <h3>Participated events ({{peserta.kegiatan_set.all|length}}):</h3>
        <ol>
            {% for kegiatan in peserta.kegiatan_set.all %}
            <li><a class="card-content" href="{{kegiatan.get_absolute_url}}">{{kegiatan.nama}}</a></li>
            {% endfor %}
        </ol>
{% endblock %}